#!/bin/sh /etc/rc.common
# Copyright (C) 2025 OpenWrt.org

START=95
STOP=10
USE_PROCD=1

PROG=/usr/bin/usque
CONFIG_DIR=/etc/usque
CONFIG_FILE=$CONFIG_DIR/config.json
PID_FILE=/var/run/usque.pid

start_service() {

    procd_open_instance
    procd_set_param command "$PROG" -c "$CONFIG_FILE" nativetun

    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile "$PID_FILE"
    procd_close_instance
}

stop_service() {
    # procd 会自动停止
    true
}

reload_service() {
    stop
    start
}