#!/bin/sh

# 修改时区
uci -q batch << EOI
set system.@system[0].zonename='Asia/Shanghai'
set system.@system[0].timezone='CST-8'
commit system
EOI

#tunsafe
mkdir -p /etc/tunsafe
wget -O /usr/bin/tunsafe https://github.com/lmq8267/tunsafe/releases/download/2025-10-09/tunsafe_aarch64-linux

exit 0
