#!/bin/sh

. /lib/functions.sh

generate_mac() {
    local prefix="$1"
    local suffix=$(dd if=/dev/urandom bs=1 count=3 2>/dev/null | hexdump -v -e '1/1 ":%02X"')
    echo "${prefix}${suffix}"
}

MAC_ETH1=$(generate_mac "04:56:65")
MAC_LAN=$(generate_mac "04:56:65")

config_load network

found_br=0
handle_br_lan() {
    local section="$1"
    local name
    config_get name "$section" name

    if [ "$name" = "br-lan" ]; then
        uci set network."$section".macaddr="$MAC_LAN"
        found_br=1
    fi
}
config_foreach handle_br_lan device

LAN_INTERFACES="eth0 lan2 lan3 lan4"

for iface in $LAN_INTERFACES; do
    section_name="${iface}_mac_fix"
    uci set network."$section_name"=device
    uci set network."$section_name".name="$iface"
    uci set network."$section_name".macaddr="$MAC_LAN"
done

uci set network.eth1_mac_fix=device
uci set network.eth1_mac_fix.name='eth1'
uci set network.eth1_mac_fix.macaddr="$MAC_ETH1"

uci commit network

/etc/init.d/network reload

exit 0

