name: Auto-Clean

on:
  # 自动清理：每天早上8点
  schedule:
    - cron: 0 0 * * *
  # 手动清理
  workflow_dispatch:

jobs:
  auto_clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
