name: Build OpenWrt
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installation depends
      run: |
        sudo apt update
        sudo apt -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
        file wget
    - name: Clone source code
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Build 
      run: |
        cd openwrt
        
        cat >> .config <<EOF
        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_64=y
        CONFIG_TARGET_x86_64_DEVICE_generic=y
        CONFIG_VMDK_IMAGES=y
        
        CONFIG_TARGET_ROOTFS_PARTSIZE=500
        
        CONFIG_LUCI_LANG_zh_Hans=y
        
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-app-openvpn=y
        CONFIG_PACKAGE_kmod-wireguard=y
        CONFIG_PACKAGE_wireguard-tools=y
        CONFIG_PACKAGE_luci-proto-wireguard=y
        EOF
        
        make defconfig
        
        make -j$(nproc) download world

    - name: Upload firmware
      uses: actions/upload-artifact@master
      with:
        name: openwrt-firmware
        path: openwrt/bin/targets/
