name: Build lede
on: 
  workflow_dispatch:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Projects
        uses: actions/checkout@v2

      - name: Delete Files
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          
      # Add caching step
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: lede/build_dir   # 缓存的目录
          key: ${{ runner.os }}-lede-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-lede-
            
      - name: Show system
        run: |
          lscpu
          free -h
          df -Th
          uname -a

      - name: Installation depends
        run: |
          sudo -E apt update -y
          sudo -E apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler \
          dos2unix ecj fakeroot fastjar flex g++-multilib gawk gcc-multilib genisoimage gettext git gnutls-dev gperf haveged help2man intltool jq libc6-dev-i386 libelf-dev \
          libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool \
          libyaml-dev libz-dev lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2 python3 python3-docutils python3-pip python3-ply python3-pyelftools \
          python3-setuptools qemu-utils quilt re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs unzip upx-ucl vim wget xmlto xxd zlib1g-dev clang g++ libncurses-dev \
          python3-distutils file
          
      - name: Clone source code
        run: |
          git clone --depth=1 --single-branch https://github.com/coolsnowwolf/lede.git
          
      - name: feeds
        run: |
          ls -a
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          
      - name: custom .config
        run: |
          cd lede
          sed -i 's/# CONFIG_IB is not set/CONFIG_IB=y/' .config
          sed -i 's/# CONFIG_SDK is not set/CONFIG_GRUB_IMAGES=y/' .config
          sed -i '508i CONFIG_SDK=y\n' .config
          sed -i 's/# CONFIG_GRUB_IMAGES is not set/CONFIG_GRUB_IMAGES=y/' .config
          sed -i 's/CONFIG_VMDK_IMAGES=y/# CONFIG_VMDK_IMAGES is not set/' .config
          sed -i 's/# CONFIG_VDI_IMAGES is not set/CONFIG_VDI_IMAGES=y/' .config
          
      - name: cat .config
        run: |
          cat lede/.config
          
      - name: download 
        run: |
          ls -a $GITHUB_WORKSPACE
          cd lede
          make defconfig
          make download
          
      - name: build
        run: |
          cd lede
          make -j5 V=s

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: LEDE-X64
          path: lede/bin/targets/x86/64/openwrt-*
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with: 
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: LEDE-x64
          draft: false
          prerelease: false
          files: lede/bin/targets/x86/64/openwrt-*
