name: Build OpenWrt
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:


    - name: Delete Files
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Show system
      run: |
        lscpu
        free -h
        df -Th
        uname -a

    - name: Installation depends
      run: |
        sudo -E apt update -y
        sudo -E apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
        mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
        libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip \
        vim wget xmlto xxd zlib1g-dev python3-setuptools
    - name: Clone source code
      run: |
        git clone https://github.com/coolsnowwolf/lede.git
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Build 
      run: |
        cd lede
        cat >> .config <<EOF
        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_64=y
        CONFIG_TARGET_x86_64_DEVICE_generic=y
        CONFIG_VMDK_IMAGES=y
        CONFIG_SDK=y
        
        CONFIG_TARGET_ROOTFS_PARTSIZE=500
        
        CONFIG_LUCI_LANG_zh_Hans=y
        CONFIG_TARGET_ROOTFS_EXT4FS=n
        CONFIG_PACKAGE_luci-app-wol=n
        CONFIG_PACKAGE_luci-app-ddns=n
        CONFIG_PACKAGE_luci-app-vlmcsd=n
        CONFIG_PACKAGE_luci-app-xlnetacc=n
        CONFIG_PACKAGE_luci-app-zerotier=n
        CONFIG_PACKAGE_luci-app-wireguard=n
        CONFIG_PACKAGE_luci-app-ipsec-vpnd=n
        CONFIG_PACKAGE_luci-app-adbyby-plus=n
        CONFIG_PACKAGE_luci-app-unblockmusic=n
        CONFIG_PACKAGE_luci-app-accesscontrol=n
        EOF
        
        make defconfig
        
        make -j$(nproc) download world

    - name: Upload firmware
      uses: actions/upload-artifact@master
      with:
        name: lede-firmware
        path: lede/bin/targets/
