name: Build OpenWrt

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Customize configuration
      run: |
        cat >> .config <<EOF
        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_64=y
        CONFIG_TARGET_x86_64_Generic=y
        CONFIG_TARGET_ROOTFS_PARTSIZE=500
        EOF

    - name: Build firmware
      run: make -j$(nproc) V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.img.gz
        
