name: Build lede
on: 
  schedule:
    - cron: '0 20 1 * *' #每月1号4点
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout Projects
        uses: actions/checkout@v2

      - name: Delete Files
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          
            
      - name: Show system
        run: |
          date
          lscpu
          free -h
          df -Th
          uname -a

      - name: Installation depends
        run: |
          sudo -E apt update -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
          genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
          libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
          libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf \
          python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
          swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          
      - name: Get Current Time
        run: |
          LEDE_TIME=$(date +"%Y-%m-%d"-"%H-%M-%S")
          echo "LEDE_TIME=$LEDE_TIME" >> $GITHUB_ENV
          
      - name: Clone source code
        run: |
          git clone --depth=1 --single-branch https://github.com/coolsnowwolf/lede.git
          
      - name: feeds
        run: |
          ls -a
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: custom .config
        run: |
          cd lede
          make defconfig
          # sed -i 's/# CONFIG_TARGET_ramips_mt7621_DEVICE_jdcloud_re-sp-01b is not set/CONFIG_TARGET_DEVICE_ramips_mt7621_DEVICE_jdcloud_re-sp-01b=y/' .config
          # sed -i 's/CONFIG_TARGET_ramips_mt7621_DEVICE_adslr_g7=y/# CONFIG_TARGET_ramips_mt7621_DEVICE_adslr_g7 is not set/' .config
          sed -i 's/# CONFIG_IB is not set/CONFIG_IB=y/' .config
          sed -i 's/# CONFIG_SDK is not set/CONFIG_SDK=y/' .config
          # sed -i 's/CONFIG_VMDK_IMAGES=y/# CONFIG_VMDK_IMAGES is not set/' .config
          # sed -i 's/# CONFIG_GRUB_IMAGES is not set/CONFIG_GRUB_IMAGES=y/' .config
          # sed -i 's/CONFIG_GRUB_EFI_IMAGES=y/# CONFIG_GRUB_EFI_IMAGES is not set/' .config
          sed -i 's/# CONFIG_MAKE_TOOLCHAIN is not set/CONFIG_MAKE_TOOLCHAIN=y/' .config

      - name: cat .config
        run: |
          cat lede/.config
          
      - name: download 
        run: |
          ls $GITHUB_WORKSPACE
          cd lede
          make download
          
      - name: build
        run: |
          cd lede
          make -j$(nproc) 
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with: 
          tag_name: lede-re-sp-01b-${{ env.LEDE_TIME }}
          body: 每月1号4点
          draft: false
          prerelease: false
          files: lede/bin/targets/x86/64/*
                  
