name: Build xg-140g-md for openwrt main
on: 
  workflow_dispatch:
jobs:
  build:
    name: ${{ matrix.source.tag_prefix }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        source:
          - name: openwrt-main
            url: https://github.com/openwrt/openwrt.git
            tag_prefix: openwrt-main-xg-140g-md
            cache_key: openwrt-main
          - name: immortalwrt-main
            url: https://github.com/immortalwrt/immortalwrt.git
            tag_prefix: immortalwrt-main-xg-140g-md
            cache_key: immortalwrt-main
    steps:
      - name: Checkout Projects
        uses: actions/checkout@v5

      - name: Clean up the system
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Installation depends
        run: |
          sudo apt update -y
          sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-setuptools rsync swig unzip zlib1g-dev file wget ccache

      - name: Clone source code
        run: |
          git clone --depth 1 ${{ matrix.source.url }} ${{ matrix.source.name }}
          cd ${{ matrix.source.name }} && ./scripts/getver.sh

      - name: move config
        run: |
          cp -af xg-140g-md/.config ${{ matrix.source.name }}/
          
          cp -af xg-140g-md/99-custom-xg-040g-md ${{ matrix.source.name }}/package/base-files/files/etc/uci-defaults/

          cp -af xg-140g-md/patch-main/target/linux/airoha/an7581/base-files/etc/board.d/02_network ${{ matrix.source.name }}/target/linux/airoha/an7581/base-files/etc/board.d/02_network

          cp -af xg-140g-md/patch-main/target/linux/airoha/dts/an7581-bell_xg-040g-md.dts ${{ matrix.source.name }}/target/linux/airoha/dts/an7581-bell_xg-040g-md.dts

          cp -af xg-140g-md/patch-main/target/linux/airoha/image/an7581.mk ${{ matrix.source.name }}/target/linux/airoha/image/an7581.mk

          sed -i 's/dnsmasq/dnsmasq-full/g' ${{ matrix.source.name }}/include/target.mk

      - name: feeds
        run: |
            cd ${{ matrix.source.name }} && ./scripts/feeds update -a && ./scripts/feeds install -a
            make defconfig

      - name: custom configuration
        run: |
          #sed -i 's/CONFIG_LINUX_6_12=y/CONFIG_LINUX_6_18=y/g' ${{ matrix.source.name }}/.config
          sed -i 's/# CONFIG_PACKAGE_luci is not set/CONFIG_PACKAGE_luci=y/g' ${{ matrix.source.name }}/.config
          sed -i 's/# CONFIG_PACKAGE_luci-app-package-manager is not set/CONFIG_PACKAGE_luci-app-package-manager=y/g' ${{ matrix.source.name }}/.config
          sed -i 's/# CONFIG_PACKAGE_luci-light is not set/CONFIG_PACKAGE_luci-light=y/g' ${{ matrix.source.name }}/.config
          sed -i 's/# CONFIG_PACKAGE_luci-theme-bootstrap is not set/CONFIG_PACKAGE_luci-theme-bootstrap=y/g' ${{ matrix.source.name }}/.config
          sed -i 's/# CONFIG_PACKAGE_luci-proto-wireguard is not set/CONFIG_PACKAGE_luci-proto-wireguard=y/g' ${{ matrix.source.name }}/.config
          sed -i 's/# CONFIG_PACKAGE_kmod-wireguard is not set/CONFIG_PACKAGE_kmod-wireguard=y/g' ${{ matrix.source.name }}/.config
          sed -i 's/# CONFIG_PACKAGE_kmod-tun is not set/CONFIG_PACKAGE_kmod-tun=y/g' ${{ matrix.source.name }}/.config
          sed -i 's/# CONFIG_PACKAGE_wireguard-tools is not set/CONFIG_PACKAGE_wireguard-tools=y/g' ${{ matrix.source.name }}/.config
          sed -i 's/# CONFIG_LUCI_LANG_zh_Hans is not set/CONFIG_LUCI_LANG_zh_Hans=y/g' ${{ matrix.source.name }}/.config
          sed -i 's/# CONFIG_PACKAGE_default-settings-chn is not set/CONFIG_PACKAGE_default-settings-chn=y/g' ${{ matrix.source.name }}/.config
          #sed -i 's/# CONFIG_PACKAGE_tunsafe is not set/CONFIG_PACKAGE_tunsafe=y/g' ${{ matrix.source.name }}/.config
          cd ${{ matrix.source.name }} && make defconfig
          
          mkdir -p files/usr/bin files/etc/init.d files/etc/tunsafe
          touch files/etc/tunsafe/tunsafe.conf
          wget -O files/usr/bin/tunsafe https://github.com/lmq8267/tunsafe/releases/download/2025-10-09/tunsafe_aarch64-linux
          cp -af $GITHUB_WORKSPACE/tunsafe/files/tunsafe files/etc/init.d/
          chmod +x files/usr/bin/tunsafe files/etc/init.d/tunsafe

          ls -R files/

      - name: Show config
        run: cat ${{ matrix.source.name }}/.config

      - name: Download
        run: |
          cd ${{ matrix.source.name }} && make -j $(nproc) download

      - name: target/linux prepare
        run: |
          #cd ${{ matrix.source.name }} && make -j $(nproc) target/linux/{clean,prepare} V=s

      - name: Build ccache
        run: |
          #cd ${{ matrix.source.name }} && make -j $(nproc) tools/ccache/compile V=s

      - name: Build
        run: |
          cd ${{ matrix.source.name }} && make -j $(nproc) V=s

      - name: Upload openwrt firmware
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ matrix.source.tag_prefix }}
          files: ${{ matrix.source.name }}/bin/targets/airoha/an7581/*
          
