name: sdk
on: 
  workflow_dispatch:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Projects
      uses: actions/checkout@v2
      
    - name: Installation depends
      run: |
        sudo -E apt update -y
        sudo -E apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
        mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
        libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip \
        vim wget xmlto xxd zlib1g-dev python3-setuptools tree
        
    - name: Clone source code
      run: |
        wget https://downloads.immortalwrt.org/releases/23.05.4/targets/x86/64/immortalwrt-sdk-23.05.4-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar -Jxf immortalwrt-sdk-*.tar.xz
        rm -rf immortalwrt-sdk*.xz

    - name: add custom package
      run: |
        cd immortalwrt-sdk*/package
        git clone --depth=1 https://github.com/science2468/luci-app-qbittorrent.git
        ls
    - name: update feed
      run: |
        cd immortalwrt-sdk*
        ./scripts/feeds update -a
        ./scripts/feeds install -a

        ./scripts/feeds update -a
        ./scripts/feeds install -a

        make defconfig
    - name: cat .config
      run: |
        cat immortalwrt-sdk*/.config
    - name: download
      run: |
        cd immortalwrt-sdk*
        make download -j$(nproc)
        tree build_dir/target-x86_64_musl/qbittorrent-sc-release-5.0.0
    - name: build
      run: |
        cd immortalwrt-sdk*
        make -j$(nproc) package/luci-app-qbittorrent/luci-app-qbittorrent-sc/compile V=99
        
    - name: Upload openwrt firmware
      uses: actions/upload-artifact@master
      with:
        name: immortalwrt-sdk
        path: immortalwrt-sdk*/bin/
