name: sdk
on: 
  workflow_dispatch:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Show system
      run: |
        lscpu
        free -h
        df -Th
        uname -a
    - name: Installation depends
      run: |
        sudo -E apt update -y
        sudo -E apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
        mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
        libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip \
        vim wget xmlto xxd zlib1g-dev python3-setuptools
    - name: Clone source code
      run: |
        wget https://downloads.immortalwrt.org/releases/23.05.2/targets/x86/64/immortalwrt-sdk-23.05.2-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar -J -x -f immortalwrt-sdk-*.tar.xz
    - name: add custom package
      run: |
        cd immortalwrt-*/package
        git clone https://github.com/destan19/OpenAppFilter.git
    - name: update feed
      run: |
        cd immortalwrt-*
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
    - name: cat .config
      run: |
        cat immortalwrt-*/.config
    - name: build
      run: |
        cd immortalwrt-*
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make -j5 package/OpenAppFilter/luci-app-oaf/compile V=s
    - name: Upload openwrt firmware
      uses: actions/upload-artifact@master
      with:
        name: immortalwrt-sdk
        path: immortalwrt-*/bin/
