name: Build xg-140g-md
on: workflow_dispatch
jobs:
  build:
    name: ${{ matrix.source.tag_prefix }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: Asia/Shanghai
    strategy:
      fail-fast: false
      matrix:
        source:
          - name: openwrt
            url: https://github.com/openwrt/openwrt/archive/refs/tags/v25.12.4.tar.gz
            tag_prefix: openwrt-xg-140g-md
            cache_key: openwrt
          - name: immortalwrt
            url: https://github.com/immortalwrt/immortalwrt/archive/refs/tags/v25.12.0.tar.gz
            tag_prefix: immortalwrt-xg-140g-md
            cache_key: immortalwrt
    steps:
      - uses: actions/checkout@v4

      - name: Clean system
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get -y autoremove --purge && sudo -E apt-get clean

      - name: Install depends
        run: |
          sudo apt update -y
          sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-setuptools rsync swig unzip zlib1g-dev file wget ccache

      - name: Clone source
        run: |
          wget ${{ matrix.source.url }}
          tar -xzf *.tar.gz
          mv $(find . -maxdepth 1 -type d -name openwrt-* -o -name immortalwrt-* | head -1) openwrt

          ./openwrt/scripts/getver.sh

          cd openwrt/package/ && git clone https://github.com/rchen14b/luci-app-airoha-npu.git
          ls

      - name: Prepare config and patches
        run: |
          rm -rf openwrt/target/linux/generic/backport-6.12/435-v6.19-mtd-spinand-add-support-for-FudanMicro-FM25S01BI3.patch

          mv -f xg-140g-md/.config openwrt/

          cp -af xg-140g-md/patch-25.12/package/boot/uboot-tools/uboot-envtools/files/mediatek_filogic openwrt/package/boot/uboot-tools/uboot-envtools/files/mediatek_filogic
          cp -af xg-140g-md/patch-25.12/package/kernel/linux/files/sysctl-nf-conntrack.conf openwrt/package/kernel/linux/files/sysctl-nf-conntrack.conf
          cp -af xg-140g-md/patch-25.12/package/kernel/linux/modules/netdevices.mk openwrt/package/kernel/linux/modules/netdevices.mk
          cp -af xg-140g-md/patch-25.12/package/base-files/files/etc/uci-defaults/99_fix-airoha-mac openwrt/package/base-files/files/etc/uci-defaults/99_fix-airoha-mac

          cp -af xg-140g-md/patch-25.12/target/linux/airoha/an7581/base-files/etc/board.d/02_network openwrt/target/linux/airoha/an7581/base-files/etc/board.d/02_network
          mkdir -p openwrt/target/linux/airoha/an7581/base-files/lib/upgrade/
          cp -af xg-140g-md/patch-25.12/target/linux/airoha/an7581/base-files/lib/upgrade/platform.sh openwrt/target/linux/airoha/an7581/base-files/lib/upgrade/platform.sh
          cp -af xg-140g-md/patch-25.12/target/linux/airoha/an7581/config-6.12 openwrt/target/linux/airoha/an7581/config-6.12
          cp -af xg-140g-md/patch-25.12/target/linux/airoha/an7581/target.mk openwrt/target/linux/airoha/an7581/target.mk
          cp -af xg-140g-md/patch-25.12/target/linux/airoha/dts/an7581.dtsi openwrt/target/linux/airoha/dts/an7581.dtsi
          cp -af xg-140g-md/patch-25.12/target/linux/airoha/dts/an7581-npu-mt7996.dtsi openwrt/target/linux/airoha/dts/an7581-npu-mt7996.dtsi
          cp -af xg-140g-md/patch-25.12/target/linux/airoha/image/an7581.mk openwrt/target/linux/airoha/image/an7581.mk
          cp -af xg-140g-md/patch-25.12/target/linux/airoha/dts/an7581-bell_xg-040g-md.dts openwrt/target/linux/airoha/dts/an7581-bell_xg-040g-md.dts
          cp -af xg-140g-md/patch-25.12/target/linux/airoha/patches-6.12/117-03-airoha_npu_eagle_add_ser.patch openwrt/target/linux/airoha/patches-6.12/117-03-airoha_npu_eagle_add_ser.patch
          cp -af xg-140g-md/patch-25.12/target/linux/airoha/patches-6.12/620-net-pcs-airoha-fix-USXGMII-rate-adaptation-on-speed.patch openwrt/target/linux/airoha/patches-6.12/620-net-pcs-airoha-fix-USXGMII-rate-adaptation-on-speed.patch
          cp -af xg-140g-md/patch-25.12/target/linux/airoha/patches-6.12/621-net-pcs-airoha-AN7581-add-global-digital-reset-for.patch openwrt/target/linux/airoha/patches-6.12/621-net-pcs-airoha-AN7581-add-global-digital-reset-for.patch
          cp -af xg-140g-md/patch-25.12/target/linux/airoha/patches-6.12/910-02-usb-pcie.patch openwrt/target/linux/airoha/patches-6.12/910-02-usb-pcie.patch
          cp -af xg-140g-md/patch-25.12/target/linux/airoha/patches-6.12/999-dsa-01-add-mt7531-netlink-support.patch openwrt/target/linux/airoha/patches-6.12/999-dsa-01-add-mt7531-netlink-support.patch

          cp -af xg-140g-md/patch-25.12/target/linux/generic/hack-6.12/400-mtd-spinand-Support-fmsh.patch openwrt/target/linux/generic/hack-6.12/400-mtd-spinand-Support-fmsh.patch
          cp -af xg-140g-md/patch-25.12/target/linux/generic/hack-6.12/430-v6.14-mtd-spinand-Introduce-a-way-to-avoid-raw-access.patch openwrt/target/linux/generic/hack-6.12/430-v6.14-mtd-spinand-Introduce-a-way-to-avoid-raw-access.patch
          cp -af xg-140g-md/patch-25.12/target/linux/generic/hack-6.12/431-v6.14-mtd-spinand-Add-support-for-SkyHigh-S35ML-3-family.patch openwrt/target/linux/generic/hack-6.12/431-v6.14-mtd-spinand-Add-support-for-SkyHigh-S35ML-3-family.patch
          cp -af xg-140g-md/patch-25.12/target/linux/generic/hack-6.12/600-mtd-spinand-add-skyhigh-robust-read-workaround.patch openwrt/target/linux/generic/hack-6.12/600-mtd-spinand-add-skyhigh-robust-read-workaround.patch

          sed -i 's/dnsmasq/dnsmasq-full/g' openwrt/include/target.mk

      - name: Cache staging_dir
        uses: actions/cache@v4
        with:
          path: openwrt/staging_dir
          key: ${{ matrix.source.cache_key }}-${{ runner.os }}-${{ hashFiles('openwrt/.config') }}
          restore-keys: ${{ matrix.source.cache_key }}-${{ runner.os }}-

      - name: Update feeds
        run: cd openwrt && ./scripts/feeds update -a && ./scripts/feeds install -a

      - name: Download sources
        run: cd openwrt && make defconfig && make -j $(nproc) download

      - name: Enable LuCI and WireGuard
        run: |
          sed -i 's/# CONFIG_PACKAGE_luci is not set/CONFIG_PACKAGE_luci=y/g' openwrt/.config
          sed -i 's/# CONFIG_PACKAGE_luci-app-package-manager is not set/CONFIG_PACKAGE_luci-app-package-manager=y/g' openwrt/.config
          sed -i 's/# CONFIG_PACKAGE_luci-light is not set/CONFIG_PACKAGE_luci-light=y/g' openwrt/.config
          sed -i 's/# CONFIG_PACKAGE_luci-theme-bootstrap is not set/CONFIG_PACKAGE_luci-theme-bootstrap=y/g' openwrt/.config
          sed -i 's/# CONFIG_PACKAGE_luci-proto-wireguard is not set/CONFIG_PACKAGE_luci-proto-wireguard=y/g' openwrt/.config
          sed -i 's/# CONFIG_PACKAGE_kmod-wireguard is not set/CONFIG_PACKAGE_kmod-wireguard=y/g' openwrt/.config
          sed -i 's/# CONFIG_PACKAGE_wireguard-tools is not set/CONFIG_PACKAGE_wireguard-tools=y/g' openwrt/.config
          sed -i 's/# CONFIG_LUCI_LANG_zh_Hans is not set/CONFIG_LUCI_LANG_zh_Hans=y/g' openwrt/.config
          sed -i 's/# CONFIG_PACKAGE_default-settings-chn is not set/CONFIG_PACKAGE_default-settings-chn=y/g' openwrt/.config
          sed -i 's/# CONFIG_PACKAGE_luci-app-cpufreq is not set/CONFIG_PACKAGE_luci-app-cpufreq=y/g' openwrt/.config
          sed -i 's/# CONFIG_PACKAGE_luci-app-airoha-npu is not set/CONFIG_PACKAGE_luci-app-airoha-npu=y/g' openwrt/.config
          cd openwrt && make defconfig

      - name: Show config
        run: cat openwrt/.config

      - name: Prepare target/linux
        run: cd openwrt && make -j $(nproc) target/linux/{clean,prepare} V=s

      - name: Build ccache
        run: cd openwrt && make -j $(nproc) tools/ccache/compile V=s

      - name: Build firmware
        run: cd openwrt && make -j $(nproc) V=s

      - name: Set datetime
        id: datetime
        run: echo datetime=$(date +'%Y%m%d%H%M%S') >> $GITHUB_OUTPUT

      - name: Upload firmware
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ matrix.source.tag_prefix }}-${{ steps.datetime.outputs.datetime }}
          files: openwrt/bin/targets/airoha/an7581/*
